### ISSUE TITLE
Manual subreddit/user input interface is awkward

### ISSUE THREAD

**Issue by kirb** [insanj/Submarine-Issues#13]
* I typed /r/thing and the app went to /r//r/thing. It's not obvious that this only wants the name. 
* I also assumed the buttons meant "go to this user" and "go to this subreddit", not "switch to inputting a user" and "go to this subreddit". 
* Input isn't validated. I entered `..` (which loaded `/r/..`, therefore expanding to `/`), and the app crashes.
* Related; there should be a failsafe that deletes the saved state if it crashed last time. Or, don't save state till it's loaded.

My suggested solution: A full reddit.com or redd.it URL should be expected, or if the input isn't a valid URL, assume it should be prefixed with `https://www.reddit.com/`. Hence, you'd enter a full URL, or /r/thing, /u/thing, or /user/thing.

**Comment by insanj** [comment]
This is all quite true. Ever since a keen user pointed out in 1.0 that a manual text field would make more sense as a search box at the top of the subreddit list (also replacing the Search Subreddit view controller), I've been preparing to do that. It also seems that I included two rather confusing buttons in that alert view rather than using Apple's `UIAlertController` or subclassing my custom alert again… This popup is definitely full of oversight, mostly because it's inclusion is just to have the barebones feature available, underestimating how often someone might actually use it (Favorites, Subscribed, Multireddits, etc, are not actually as useful as I thought, particularly because new subreddits are frequently the destination of manual entries).

This entire process will be remade, similar to how that user suggested so, in 1.2!

**Comment by insanj** [comment]
Manual User and Subreddit are now separate actions :)
